services:
  - type: web
    name: kirana-erp
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DB_MODE
        value: pgmem
      - key: AUTO_SEED_ADMIN
        value: "1"
      - key: SEED_ADMIN_USERNAME
        value: admin
      - key: SEED_ADMIN_PASSWORD
        value: "Admin@123"
      - key: TRUST_PROXY
        value: "1"
      - key: CORS_ORIGIN
        value: https://sachinranafiit-eng.github.io
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CUSTOMER_JWT_SECRET
        generateValue: true
      - key: SETUP_TOKEN
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
