import React,{useState} from 'react';
import {Upload,Download,Plus,Trash2} from 'lucide-react';
import schemas from '../shared/import-schemas.json';
export default function BulkImport({initialKind='products',api,refresh,can=()=>true}){
 const[kind,setKind]=useState(initialKind),[rows,setRows]=useState([]),[text,setText]=useState(''),[errors,setErrors]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[pin,setPin]=useState(''),[key,setKey]=useState(crypto.randomUUID());
 const schema=schemas[kind],cols=schema.columns;
 function edit(next){setRows(next);setKey(crypto.randomUUID());setStatus('');}
 async function template(format){try{const r=await api(`/imports/template?kind=${kind}&format=${format}`),bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:r.mime}));const a=document.createElement('a');a.href=url;a.download=r.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setStatus(e.message);}}
 async function upload(f){if(!f)return;setBusy(true);setStatus('');try{if(f.size>5*1024*1024)throw Error('Maximum file size is 5 MB');let s='';for(const b of new Uint8Array(await f.arrayBuffer()))s+=String.fromCharCode(b);const r=await api('/imports/preview',{method:'POST',body:{kind,fileName:f.name,base64:btoa(s)}});edit(r.rows);setText(r.text||'');setErrors(r.errors||[]);}catch(e){setStatus(e.message);}finally{setBusy(false);}}
 return <section className="bulk-import panel padded"><h3>Bulk add & file templates</h3><p>Download a template, replace the example row with your data, then upload and review it. You can also type rows directly.</p><label className="field">What would you like to add?<select aria-label="Import type" value={kind} disabled={busy} onChange={e=>{setKind(e.target.value);edit([]);setText('');setErrors([]);}}>{Object.entries(schemas).filter(([,s])=>s.permission.every(can)).map(([k,s])=><option key={k} value={k}>{s.label}</option>)}</select></label><div className="notice">{schema.help}</div><div className="row-actions bulk-actions"><button className="btn" disabled={busy} onClick={()=>template('csv')}><Download size={16}/>Download CSV template</button><button className="btn" disabled={busy} onClick={()=>template('xlsx')}><Download size={16}/>Download Excel template</button></div><div className="import-upload"><Upload size={28}/><h3>Upload {schema.label.toLowerCase()}</h3><p>CSV / XLSX / text PDF · 5 MB · maximum 500 rows</p><input aria-label="Upload bulk file" type="file" accept=".csv,.xlsx,.pdf" disabled={busy} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/></div>{text&&<details><summary>Extracted PDF text</summary><textarea className="pdf-text" readOnly value={text}/></details>}{errors.map((e,i)=><p className="error" key={i}>{e}</p>)}{rows.length>0&&<><h3>Review {rows.length} rows</h3><div className="table-wrap import-table"><table><thead><tr><th>ROW</th>{cols.map(k=><th key={k}>{k}</th>)}<th>REMOVE</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{i+1}</td>{cols.map(k=><td key={k}><input disabled={busy} aria-label={`${k} row ${i+1}`} value={r[k]??''} onChange={e=>edit(rows.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></td>)}<td><button aria-label={`Remove row ${i+1}`} className="icon-btn" disabled={busy} onClick={()=>edit(rows.filter((_,n)=>n!==i))}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></>}{kind==='stock'&&<label className="field">Your stock adjustment PIN (if configured)<input type="password" value={pin} onChange={e=>setPin(e.target.value)} autoComplete="off"/></label>}<div className="modal-actions"><button className="btn" disabled={busy||rows.length>=500} onClick={()=>edit([...rows,{}])}><Plus size={16}/>Add row</button><button className="btn primary" disabled={busy||!rows.length} onClick={async()=>{setBusy(true);setStatus('');try{const result=await api('/imports/commit',{method:'POST',body:{kind,rows,requestKey:key,pin}});setRows([]);setKey(crypto.randomUUID());setErrors([]);setStatus(`${result.count} ${schema.label.toLowerCase()} saved successfully.`);refresh();}catch(e){setStatus(e.message);}finally{setBusy(false);}}}>{busy?'Processing…':`Save ${rows.length||''} ${schema.label.toLowerCase()}`}</button></div><p className="data-note">If any row fails, the whole batch is rolled back. Correct the reported row and try again.</p>{status&&<div role="status" className="notice">{status}</div>}</section>;
}
