import React,{useState} from 'react';
import {User,ShieldCheck} from 'lucide-react';
export default function CustomerAuth({api,otpConfigured,onSuccess}){
 const[mode,setMode]=useState('login'),[values,setValues]=useState({username:'',password:'',confirm:'',name:'',mobile:'',otp:''}),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const set=(k,v)=>setValues(x=>({...x,[k]:v}));
 function changeMode(next){setMode(next);setError('');setSent(false);setValues(v=>({...v,password:'',confirm:'',otp:''}));}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{let result;if(mode==='otp'){if(!sent){await api('/auth/request-otp',{mobile:values.mobile});setSent(true);return;}result=await api('/auth/verify-otp',{mobile:values.mobile,otp:values.otp,name:values.name});}else if(mode==='register'){if(values.password!==values.confirm)throw Error('The passwords do not match');result=await api('/auth/register',{username:values.username,password:values.password,name:values.name,mobile:values.mobile});}else result=await api('/auth/login',{username:values.username,password:values.password});onSuccess(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><div className="shop-login-icon"><User size={32}/></div><div className="shop-auth-tabs"><button disabled={busy} className={mode==='login'?'selected':''} onClick={()=>changeMode('login')}>Sign in</button><button disabled={busy} className={mode==='register'?'selected':''} onClick={()=>changeMode('register')}>Create account</button>{otpConfigured&&<button disabled={busy} className={mode==='otp'?'selected':''} onClick={()=>changeMode('otp')}>SMS OTP</button>}</div><p>{mode==='register'?'Create your customer account to order groceries and track deliveries.':mode==='login'?'Welcome back. Sign in with your customer username and password.':'Enter your mobile number to receive a sign-in code.'}</p>{error&&<div className="shop-alert" role="alert">{error}</div>}<form onSubmit={submit}>
 {mode!=='otp'&&<label>Username<input name="username" autoComplete="username" required minLength={3} maxLength={40} pattern="[A-Za-z0-9][A-Za-z0-9._-]{2,39}" value={values.username} onChange={e=>set('username',e.target.value)} disabled={busy}/></label>}
 {(mode==='register'||(mode==='otp'&&sent))&&<label>Your name<input name="name" autoComplete="name" required maxLength={150} value={values.name} onChange={e=>set('name',e.target.value)} disabled={busy}/></label>}
 {(mode==='register'||mode==='otp')&&<label>Contact mobile number<input name="mobile" type="tel" autoComplete="tel-national" required pattern="[0-9]{10}" maxLength={10} value={values.mobile} onChange={e=>set('mobile',e.target.value)} disabled={busy||(mode==='otp'&&sent)}/></label>}
 {mode!=='otp'&&<label>Password<input name="password" type="password" autoComplete={mode==='register'?'new-password':'current-password'} required minLength={mode==='register'?10:undefined} maxLength={72} value={values.password} onChange={e=>set('password',e.target.value)} disabled={busy}/></label>}
 {mode==='register'&&<><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" required minLength={10} maxLength={72} value={values.confirm} onChange={e=>set('confirm',e.target.value)} disabled={busy}/></label><p className="shop-small">Use at least 10 characters. Keep your username and password safe. Your contact number is used for delivery; signing in uses your password.</p></>}
 {mode==='otp'&&sent&&<><label>6-digit OTP<input name="otp" required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={values.otp} onChange={e=>set('otp',e.target.value)} disabled={busy}/></label><button type="button" className="shop-text-btn" disabled={busy} onClick={()=>setSent(false)}>Change number / resend code</button></>}
 <button className="shop-primary" disabled={busy}>{busy?'Please wait…':mode==='register'?'Create account & continue':mode==='login'?'Sign in & continue':sent?'Verify & continue':'Send OTP'}</button></form><p className="shop-small"><ShieldCheck size={13}/> Customer accounts are separate from staff ERP accounts.</p></>;
}
export function CustomerPassword({api,onChanged}){const[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form onSubmit={async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));if(b.newPassword!==b.confirm){setError('The passwords do not match');return;}setBusy(true);try{await api('/account/password',b);onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}}><p>Changing your password signs you out on every device.</p><label>Current password<input type="password" name="currentPassword" autoComplete="current-password" required/></label><label>New password<input type="password" name="newPassword" autoComplete="new-password" minLength={10} maxLength={72} required/></label><label>Confirm new password<input type="password" name="confirm" autoComplete="new-password" minLength={10} maxLength={72} required/></label>{error&&<div className="shop-alert" role="alert">{error}</div>}<button className="shop-primary" disabled={busy}>{busy?'Saving…':'Change password'}</button></form>;}
