import React,{useState,useEffect} from 'react';
import {Search,ShoppingBag,MapPin,Clock,ChevronRight,Plus,Minus,X,User,ArrowLeft,Package,CheckCircle,Truck,Leaf,ShieldCheck} from 'lucide-react';
import './storefront.css';
const API_BASE=(import.meta.env.VITE_API_BASE||'').replace(/\/$/,'');
const backendError='The online store backend is not connected. Deploy the ERP API or open the local server.';
const pagesWithoutApi=location.hostname.endsWith('.github.io')&&!API_BASE;
import CustomerAuth,{CustomerPassword} from './customer-auth.jsx';
const BASE_PATH=import.meta.env.BASE_URL||'/';
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v||0));
const art=name=>{const s=name.toLowerCase();return /milk|dairy|paneer|butter|cheese|curd/.test(s)?'🥛':/atta|flour|rice|dal|staple/.test(s)?'🌾':/tea|coffee|drink|juice|beverage/.test(s)?'☕':/biscuit|snack|chips|noodle|bread|bakery/.test(s)?'🍪':/soap|shampoo|personal/.test(s)?'🧴':/clean|detergent|household/.test(s)?'🧽':/oil|ghee/.test(s)?'🫙':/spice|masala|salt|sugar/.test(s)?'🧂':'🛍️';};
const price=p=>Math.round(Number(p.sale_price)*(p.tax_inclusive===false?1+Number(p.gst_rate)/100:1)*100)/100;
function saved(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
export default function Storefront(){
 const[account,setAccount]=useState(null);
 const[products,setProducts]=useState([]),[cfg,setCfg]=useState(null),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[sort,setSort]=useState('name'),[basket,setBasket]=useState(()=>saved('kirana-basket',{})),[drawer,setDrawer]=useState(''),[token,setToken]=useState(sessionStorage.getItem('kirana-customer')||''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[delivery,setDelivery]=useState('pickup'),[paymentMode,setPaymentMode]=useState('cod'),[address,setAddress]=useState(()=>saved('kirana-address',{line1:'',city:'',pincode:''})),[orders,setOrders]=useState([]),[detail,setDetail]=useState(null),[quote,setQuote]=useState(null),[quoteError,setQuoteError]=useState(''),[notice,setNotice]=useState('');
 async function api(path,body,method){const r=await fetch(API_BASE+'/api/v1/storefront'+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const text=await r.text();let j;try{j=JSON.parse(text);}catch{throw Error(backendError);}if(r.status===401){sessionStorage.removeItem('kirana-customer');setToken('');}if(!r.ok)throw Error(j.message||'Could not connect to the store');return j.data;}
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function catalog(){setLoading(true);try{if(pagesWithoutApi)throw Error(backendError);const c=await api('/config');setCfg(c);if(!c.enabled){setProducts([]);return;}let all=[],page=1;while(true){const rows=await api('/products?pageSize=100&page='+page++);all.push(...rows);if(rows.length<100)break;}setProducts(all);}finally{setLoading(false);}}
 useEffect(()=>{run(catalog);const link=document.createElement('link');link.rel='manifest';link.href=BASE_PATH+'manifest.webmanifest';document.head.appendChild(link);if('serviceWorker' in navigator)navigator.serviceWorker.register(BASE_PATH+'shop-sw.js',{scope:BASE_PATH+'store'}).catch(()=>{});return()=>link.remove();},[]);
 useEffect(()=>{if(!cfg?.paymentGateway?.configured||window.Razorpay)return;const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;document.head.appendChild(script);return()=>script.remove();},[cfg]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&!busy)catalog().catch(()=>{});};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[busy]);
 useEffect(()=>{localStorage.setItem('kirana-basket',JSON.stringify(basket));},[basket]);
 const items=products.filter(p=>Number(basket[p.id])>0).map(p=>({...p,quantity:Number(basket[p.id])}));
 const input=items.map(p=>({productId:p.id,quantity:p.quantity}));const signature=JSON.stringify(input);
 useEffect(()=>{let active=true;setQuote(null);setQuoteError('');if(!items.length)return;const id=setTimeout(()=>api('/quote',{items:input,deliveryType:delivery}).then(q=>active&&setQuote(q)).catch(e=>active&&setQuoteError(e.message)),200);return()=>{active=false;clearTimeout(id);};},[signature,delivery]);
 useEffect(()=>{if(drawer==='orders'&&token)run(async()=>{setOrders(await api('/orders'));setAccount(await api('/account'));});},[drawer,token]);
 function change(p,delta){setQuote(null);setBasket(b=>{const n=Math.max(0,Math.min(Number(p.available_qty),Number(b[p.id]||0)+delta));return {...b,[p.id]:n};});}
 const categories=['All',...new Set(products.map(p=>p.category_name||'Essentials'))];
 const shown=products.filter(p=>(category==='All'||(p.category_name||'Essentials')===category)&&[p.name,p.local_name,p.category_name].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='low'?price(a)-price(b):sort==='high'?price(b)-price(a):a.name.localeCompare(b.name));
 const qty=items.reduce((s,i)=>s+i.quantity,0),subtotal=items.reduce((s,i)=>s+price(i)*i.quantity,0),available=cfg?.enabled&&!loading;
 function counter(p){const q=Number(basket[p.id]||0);return q?<div className="shop-counter"><button disabled={busy} aria-label={'Remove one '+p.name} onClick={()=>change(p,-1)}><Minus size={14}/></button><b>{q}</b><button disabled={busy||q>=Number(p.available_qty)} aria-label={'Add one '+p.name} onClick={()=>change(p,1)}><Plus size={14}/></button></div>:<button className="shop-add" disabled={busy||Number(p.available_qty)<1} onClick={()=>change(p,1)}>ADD <Plus size={14}/></button>;}
 async function place(){await run(async()=>{await api('/cart',{items:input},'PUT');let o;if(paymentMode==='online'){const po=await api('/payment/order',{deliveryType:delivery});if(!window.Razorpay)throw Error('Online payment checkout is still loading. Please try again.');o=await new Promise((resolve,reject)=>{const rzp=new window.Razorpay({key:po.keyId,amount:po.amount,currency:po.currency,name:cfg?.name||'Kirana & Co.',description:'Online store order',order_id:po.orderId,prefill:{name:account?.name,email:account?.email,contact:account?.mobile},handler:async response=>{try{resolve(await api('/orders',{deliveryType:delivery,deliveryAddress:delivery==='delivery'?address:{},paymentMode:'online',gatewayOrderId:po.orderId,paymentReference:response.razorpay_payment_id,gatewaySignature:response.razorpay_signature}));}catch(e){reject(e);}}});rzp.on('payment.failed',()=>reject(Error('Payment failed. Your order was not placed.')));rzp.open();});}else{o=await api('/orders',{deliveryType:delivery,deliveryAddress:delivery==='delivery'?address:{},paymentMode:'cod'});}setBasket({});localStorage.setItem('kirana-address',JSON.stringify(address));setNotice('Order placed! '+o.order_number);setDrawer('orders');setOrders(await api('/orders'));await catalog();});}
 return <div className="shop"><header className="shop-header"><a className="shop-brand" href={BASE_PATH+'store'}><span><Leaf size={27}/></span><b>{cfg?.name||'Kirana & Co.'}<small>YOUR NEIGHBOURHOOD STORE</small></b></a><button className="shop-location" onClick={()=>setDrawer('location')}><MapPin size={20}/><span><b>{delivery==='pickup'?'Store pickup':'Home delivery'}</b><small>{delivery==='pickup'?'Shop online, collect in store':address.pincode||'Set your delivery location'}</small></span><ChevronRight size={17}/></button><label className="shop-search"><Search size={21}/><input aria-label="Search groceries" placeholder='Search for “milk”, “rice”, “snacks”…' value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={16}/></button>}</label><button className="shop-account" onClick={()=>setDrawer(token?'orders':'login')}><User size={21}/><span>{token?'My orders':'Login'}</span></button><button className="shop-cart" onClick={()=>setDrawer('cart')}><ShoppingBag size={21}/><span>{qty?`${qty} items`:'My basket'}<small>{qty?money(subtotal):'Start shopping'}</small></span></button></header>
 <div className="shop-body">{error&&<div className="shop-alert" role="alert">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="shop-success" role="status"><CheckCircle size={18}/>{notice}</div>}{!search&&category==='All'&&<><section className="shop-hero"><div><span className="shop-eyebrow">THE GOOD STUFF. CLOSE TO HOME.</span><h1>Your daily essentials,<br/><em>one happy basket.</em></h1><p>{cfg?.banner||'Fresh picks and everyday favourites from your local store.'}</p><button onClick={()=>document.getElementById('shop-products').scrollIntoView({behavior:'smooth'})}>Explore the store <ChevronRight size={18}/></button><div className="shop-hero-note"><ShieldCheck size={16}/>Pay on pickup or delivery</div></div><div className="shop-hero-art" aria-hidden="true"><span>🥦</span><span>🥛</span><span>🍊</span><span>🛍️</span><span>🥖</span><div className="shop-fresh-stamp">LOCAL STORE<br/><b>Everyday<br/>goodness</b><Leaf size={20}/></div></div></section><div className="shop-promises"><span><Package/>Everyday essentials</span><span><Truck/>{cfg?.deliveryEta||'Pickup & local delivery'}</span><span><ShieldCheck/>Prices include applicable GST</span></div></>}
 <section className="shop-categories" aria-label="Shop by category">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}><span>{c==='All'?'🏪':art(c)}</span><b>{c==='All'?'Shop all':c}</b></button>)}</section><section id="shop-products"><div className="shop-section-title"><div><h2>{search?`Results for “${search}”`:category==='All'?'Everyday favourites':category}</h2><p>{loading?'Finding your favourites…':`${shown.length} products · live store availability`}</p></div><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name: A to Z</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>{loading?<div className="shop-grid">{Array.from({length:6},(_,i)=><div className="shop-skeleton" key={i}/>)}</div>:!available?<div className="shop-empty"><Clock size={35}/><h3>The online store is closed</h3><p>Please check back when your local store reopens.</p></div>:!shown.length?<div className="shop-empty"><Search size={35}/><h3>No products found</h3><p>Try another search or category.</p><button onClick={()=>{setSearch('');setCategory('All');}}>View all products</button></div>:<div className="shop-grid">{shown.map(p=><article className="shop-product" key={p.id}><div className="shop-product-art">{Array.isArray(p.online_images)&&/^https:\/\//.test(p.online_images[0]||'')?<img src={p.online_images[0]} alt={p.name} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none';}}/>:<span aria-hidden="true">{art(p.name+' '+p.category_name)}</span>}{Number(p.mrp)>price(p)&&<small className="shop-saving">SAVE {money(Number(p.mrp)-price(p))}</small>}</div><span className={'shop-stock '+(Number(p.available_qty)<1?'out':'')}><span/>{Number(p.available_qty)>=1?'In stock':'Sold out'}</span><h3>{p.name}</h3><p>{p.unit||'pack'}{p.online_description?' · '+p.online_description:''}</p><div className="shop-product-bottom"><div><b>{money(price(p))}</b>{Number(p.mrp)>price(p)&&<del>{money(p.mrp)}</del>}</div>{counter(p)}</div></article>)}</div>}</section><footer className="shop-footer"><b>{cfg?.name||'Kirana & Co.'}</b><p>Good things from your neighbourhood. Pickup and local delivery.</p><a href={BASE_PATH}>Store team login</a></footer></div>
 {qty>0&&<button className="shop-mobile-basket" onClick={()=>setDrawer('cart')}><ShoppingBag size={19}/><span>{qty} items · {money(subtotal)}</span><b>View basket →</b></button>}
 {drawer&&<div className="shop-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy){setDrawer('');setDetail(null);}}}><section className="shop-drawer" role="dialog" aria-modal="true" aria-label={drawer==='cart'?'Your basket':drawer==='orders'?'My orders':drawer==='location'?'Delivery location':'Customer login'}><div className="shop-drawer-title"><h2>{drawer==='cart'?'Your basket':drawer==='orders'?'My orders':drawer==='location'?'Pickup or delivery':drawer==='password'?'Change your password':'Welcome to your local store'}</h2><button aria-label="Close panel" disabled={busy} onClick={()=>{setDrawer('');setDetail(null);}}><X size={22}/></button></div>{error&&<div className="shop-alert" role="alert">{error}</div>}
 {drawer==='location'&&<><p>Choose how you’d like to receive your groceries.</p><div className="shop-delivery-options">{['pickup','delivery'].map(v=><button className={delivery===v?'selected':''} key={v} onClick={()=>setDelivery(v)}>{v==='pickup'?<Package/>:<Truck/>}{v==='pickup'?'Store pickup':'Home delivery'}<small>{v==='pickup'?'No delivery fee':money(cfg?.deliveryCharge)}</small></button>)}</div>{delivery==='delivery'&&<><label>Pincode<input value={address.pincode} maxLength={6} inputMode="numeric" onChange={e=>setAddress({...address,pincode:e.target.value})}/></label><p>{cfg?.pincodes?.length?`We deliver to ${cfg.pincodes.join(', ')}`:cfg?.deliveryEta}</p></>}<button className="shop-primary" onClick={()=>setDrawer('')}>Save preference</button></>}
 {drawer==='login'&&<CustomerAuth api={api} otpConfigured={cfg?.otpConfigured} onSuccess={r=>{sessionStorage.setItem('kirana-customer',r.token);setToken(r.token);setError('');setDrawer(items.length?'cart':'orders');}}/>}
 {drawer==='password'&&<CustomerPassword api={api} onChanged={()=>{sessionStorage.removeItem('kirana-customer');setToken('');setDrawer('login');setNotice('Password changed. Sign in with your new password.');}}/>}
 {drawer==='cart'&&(!items.length?<div className="shop-empty"><ShoppingBag size={48}/><h3>Your basket is waiting</h3><p>Add your everyday favourites to get started.</p><button className="shop-primary" onClick={()=>setDrawer('')}>Start shopping</button></div>:<><div className="shop-basket-list">{items.map(p=><div className="shop-basket-row" key={p.id}><span className="shop-basket-art">{art(p.name)}</span><div><b>{p.name}</b><small>{money(price(p))} · {p.unit}</small></div>{counter(p)}</div>)}</div><div className="shop-delivery-options">{['pickup','delivery'].map(v=><button disabled={busy} key={v} className={delivery===v?'selected':''} onClick={()=>setDelivery(v)}>{v==='pickup'?'Store pickup':'Home delivery'}<small>{v==='pickup'?'No delivery fee':money(cfg?.deliveryCharge)}</small></button>)}</div>{delivery==='delivery'&&<><p className="shop-small">{cfg?.deliveryEta}</p>{[['line1','House, street & landmark'],['city','City'],['pincode','6-digit pincode']].map(([k,label])=><label key={k}>{label}<input disabled={busy} maxLength={k==='pincode'?6:k==='city'?100:500} value={address[k]} onChange={e=>setAddress({...address,[k]:e.target.value})}/></label>)}</>}
 <label className="shop-payment-select">Payment method<select disabled={busy} value={paymentMode} onChange={e=>setPaymentMode(e.target.value)}><option value="cod">Cash on {delivery==='pickup'?'pickup':'delivery'}</option><option value="online" disabled={!cfg?.paymentGateway?.configured}>Online payment (Razorpay · UPI / card)</option></select></label>{paymentMode==='online'&&!cfg?.paymentGateway?.configured&&<p className="shop-alert">Online payment is not configured by the store yet. Choose cash on pickup/delivery.</p>}<div className="shop-bill"><h3>Bill details</h3><div><span>Items total (includes GST)</span><b>{quote?money(quote.subtotal):'Calculating…'}</b></div><div><span>Delivery</span><b>{quote?quote.deliveryCharge?money(quote.deliveryCharge):'FREE':'—'}</b></div><div className="shop-bill-total"><b>To pay</b><b>{quote?money(quote.total):'—'}</b></div><p>{paymentMode==='online'?'Secure payment by Razorpay. UPI, cards and net banking are supported.':('Payment on '+(delivery==='pickup'?'pickup':'delivery')+'.')}</p></div>{quoteError&&<div className="shop-alert">{quoteError}</div>}{quote&&quote.subtotal<quote.minimumOrder&&<p className="shop-alert">Add {money(quote.minimumOrder-quote.subtotal)} more to meet the minimum order.</p>}<button className="shop-primary" disabled={busy||!quote||quote.subtotal<quote.minimumOrder||!available||(paymentMode==='online'&&!cfg?.paymentGateway?.configured)} onClick={()=>token?place():setDrawer('login')}>{busy?'Placing your order…':token?'Place order · '+money(quote?.total):'Login to checkout'}</button><p className="shop-small">Stock and prices are checked again when you place your order.</p></>)}
 {drawer==='orders'&&<>{detail?<><button className="shop-text-btn" onClick={()=>setDetail(null)}><ArrowLeft size={16}/>All orders</button><h3>{detail.order_number}</h3><div className="shop-timeline">{detail.history.map((h,i)=><div key={i}><CheckCircle size={19}/><div><b>{h.status.replaceAll('_',' ')}</b><small>{new Date(h.created_at).toLocaleString('en-IN')}</small></div></div>)}</div>{detail.items.map(i=><div className="shop-order-line" key={i.id}><span>{i.name} × {i.quantity}</span><b>{money(i.total_amount)}</b></div>)}<div className="shop-order-line"><span>Delivery</span><b>{money(detail.delivery_charge)}</b></div><div className="shop-order-line"><b>Total</b><b>{money(detail.total_amount)}</b></div></>:<><button className="shop-text-btn" disabled={busy} onClick={()=>run(async()=>setOrders(await api('/orders')))}>Refresh orders</button>{!orders.length&&<div className="shop-empty"><Package size={36}/><h3>No orders yet</h3><p>Your orders will appear here.</p></div>}{orders.map(o=><button key={o.id} className="shop-order" onClick={()=>run(async()=>setDetail(await api('/orders/'+o.id)))}><div><b>{o.order_number}</b><small>{new Date(o.created_at).toLocaleDateString('en-IN')}</small></div><span className="shop-order-status">{o.status}</span><strong>{money(o.total_amount)}</strong><ChevronRight size={17}/></button>)}{account?.username&&<p className="shop-small">Signed in as {account.username}</p>}{account?.canChangePassword&&<button className="shop-text-btn" onClick={()=>setDrawer('password')}>Change password</button>}<button className="shop-text-btn" disabled={busy} onClick={()=>run(async()=>{await api('/account/logout',{});sessionStorage.removeItem('kirana-customer');setToken('');setOrders([]);setAccount(null);setDrawer('');})}>Sign out</button></>}</>}
 </section></div>}
 </div>;
}
