const router=require('express').Router();
const {query,withTransaction,dump,embedded}=require('../config/db');
const {authenticate}=require('../middleware/auth.middleware');
const {requirePermission:permit,requirePin}=require('../middleware/rbac.middleware');
const ah=require('../utils/asyncHandler');const E=require('../utils/ApiError');const op=require('../services/operations');const D=require('decimal.js');
const send=(res,data)=>res.json({success:true,data});const store=u=>u.store_id||1;
router.use(authenticate);
router.get('/bootstrap',ah(async(req,res)=>{const data={};data.stores=(await query('SELECT * FROM stores WHERE is_active=true ORDER BY id')).rows;data.store=data.stores.find(s=>s.id===store(req.user));data.settings=Object.fromEntries((await query("SELECT key,value FROM settings WHERE key IN('demo_mode','receipt_footer','invoice_prefix')")).rows.map(r=>[r.key,r.value]));send(res,data);}));
router.get('/sales',permit('sales.view'),ah(async(req,res)=>{
 const sql= require('../config/db').memory
  ? "SELECT s.*,c.name customer_name,u.full_name cashier_name,0 returned_amount FROM sales s LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN users u ON u.id=s.cashier_id WHERE s.store_id=$1 ORDER BY s.created_at DESC LIMIT 500"
  : "SELECT s.*,c.name customer_name,u.full_name cashier_name,COALESCE((SELECT SUM(amount) FROM sales_returns WHERE sale_id=s.id),0) returned_amount FROM sales s LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN users u ON u.id=s.cashier_id WHERE s.store_id=$1 ORDER BY s.created_at DESC LIMIT 500";
 send(res,(await query(sql,[store(req.user)])).rows);
}));
router.post('/sales',permit('sales.add'),ah(async(req,res)=>send(res,await op.sale(req.user,req.body))));
router.get('/sales/:id',permit('sales.view'),ah(async(req,res)=>{const sale=(await query('SELECT s.*,c.name customer_name,c.mobile,c.address customer_address,c.gstin customer_gstin FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.id=$1 AND s.store_id=$2',[req.params.id,store(req.user)])).rows[0];if(!sale)throw E.notFound('Invoice not found');let items=(await query('SELECT i.*,p.name,p.hsn_code,u.short_code unit,COALESCE((SELECT SUM(quantity) FROM sales_returns r WHERE r.sale_item_id=i.id),0) returned_qty FROM sale_items i JOIN products p ON p.id=i.product_id JOIN units u ON u.id=p.unit_id WHERE sale_id=$1',[sale.id])).rows;if(!op.can(req.user,'pricing.view_cost_price'))items=items.map(({cost_price_snapshot,...x})=>x);send(res,{...sale,items,store:(await query('SELECT * FROM stores WHERE id=$1',[sale.store_id])).rows[0],returns:(await query('SELECT * FROM sales_returns WHERE sale_id=$1',[sale.id])).rows});}));
router.post('/sales/:id/return',permit('sales.return'),requirePin,ah(async(req,res)=>send(res,await withTransaction(async c=>{
 const s=(await c.query('SELECT * FROM sales WHERE id=$1 AND store_id=$2 FOR UPDATE',[req.params.id,store(req.user)])).rows[0];if(!s||s.status!=='completed'||s.invoice_type==='quotation')throw E.badRequest('Only completed sales can be returned');const i=(await c.query('SELECT i.*,p.hsn_code FROM sale_items i JOIN products p ON p.id=i.product_id WHERE i.id=$1 AND sale_id=$2',[req.body.itemId,s.id])).rows[0];if(!i)throw E.notFound('Invoice item not found');const used=(await c.query('SELECT COALESCE(SUM(quantity),0) n FROM sales_returns WHERE sale_item_id=$1',[i.id])).rows[0].n;const qty=op.number(req.body.quantity,'return quantity',.001,Number(i.quantity)-Number(used));if(!req.body.reason)throw E.badRequest('Return reason required');const amount=op.money(new D(i.total_amount).mul(qty).div(i.quantity)),taxable=op.money(new D(i.taxable_amount).mul(qty).div(i.quantity));const mode=req.body.refundMode||'cash';if(!['cash','upi','card','credit','bank'].includes(mode)||mode==='credit'&&!s.customer_id)throw E.badRequest('Invalid refund method');
 const r=(await c.query('INSERT INTO sales_returns(sale_id,product_id,sale_item_id,quantity,reason,amount,taxable_amount,cost_amount,refund_mode,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[s.id,i.product_id,i.id,qty,req.body.reason,amount,taxable,req.body.restock===false?0:op.money(new D(qty).mul(i.cost_price_snapshot)),mode,req.user.id])).rows[0];if(req.body.restock!==false)await op.movement(c,req.user,i.product_id,qty,'sale_return','sales_return',r.id,i.batch_id);await op.taxrow(c,'sale',s.id,{...i,taxable_amount:-taxable,tax:op.money(taxable-amount)},Number(s.igst_amount)>0);
 if(s.customer_id){await c.query('INSERT INTO credit_notes(customer_id,sale_id,amount,reason) VALUES($1,$2,$3,$4)',[s.customer_id,s.id,amount,req.body.reason]);if(mode!=='credit')await c.query("INSERT INTO payments(party_type,party_id,reference_type,reference_id,amount,mode,created_by,store_id,notes) VALUES('customer',$1,'refund',$2,$3,$4,$5,$6,$7)",[s.customer_id,s.id,-amount,mode,req.user.id,store(req.user),req.body.reason]);}
 await op.audit(c,req.user,'sales.return','sales_returns',r.id,{amount,quantity:qty});return r;
}))));
router.post('/sales/:id/cancel',permit('sales.cancel'),requirePin,ah(async(req,res)=>send(res,await withTransaction(async c=>{const s=(await c.query('SELECT * FROM sales WHERE id=$1 AND store_id=$2 FOR UPDATE',[req.params.id,store(req.user)])).rows[0];if(!s||s.status==='cancelled')throw E.badRequest('Invoice already cancelled or missing');if(!req.body.reason)throw E.badRequest('Reason required');if((await c.query('SELECT id FROM sales_returns WHERE sale_id=$1',[s.id])).rows.length)throw E.badRequest('Invoice has returns; use remaining item returns instead');if(s.invoice_type!=='quotation'){for(const i of (await c.query('SELECT i.*,p.hsn_code FROM sale_items i JOIN products p ON p.id=i.product_id WHERE sale_id=$1',[s.id])).rows){await op.movement(c,req.user,i.product_id,Number(i.quantity),'sale_return','cancel',s.id,i.batch_id);await op.taxrow(c,'sale',s.id,{...i,taxable_amount:-Number(i.taxable_amount),tax:op.money(Number(i.taxable_amount)-Number(i.total_amount))},Number(s.igst_amount)>0);}if(s.customer_id)for(const p of (await c.query("SELECT * FROM payments WHERE reference_type='sale' AND reference_id=$1",[s.id])).rows)await c.query("INSERT INTO payments(party_type,party_id,reference_type,reference_id,amount,mode,created_by,store_id,notes) VALUES('customer',$1,'cancel',$2,$3,$4,$5,$6,$7)",[s.customer_id,s.id,-Number(p.amount),p.mode,req.user.id,store(req.user),req.body.reason]);}await c.query("UPDATE sales SET status='cancelled',notes=$1 WHERE id=$2",[req.body.reason,s.id]);await op.audit(c,req.user,'sales.cancel','sales',s.id,{reason:req.body.reason});return {id:s.id};}))));
router.get('/held',permit('sales.add'),ah(async(req,res)=>send(res,(await query('SELECT * FROM held_carts WHERE store_id=$1 ORDER BY created_at DESC',[store(req.user)])).rows)));
router.post('/held',permit('sales.add'),ah(async(req,res)=>{if(!req.body.name||!req.body.cart)throw E.badRequest('Name and cart required');send(res,(await query('INSERT INTO held_carts(store_id,name,cart,created_by) VALUES($1,$2,$3,$4) RETURNING *',[store(req.user),String(req.body.name).slice(0,100),JSON.stringify(req.body.cart),req.user.id])).rows[0]);}));
router.delete('/held/:id',permit('sales.add'),ah(async(req,res)=>{await query('DELETE FROM held_carts WHERE id=$1 AND store_id=$2',[req.params.id,store(req.user)]);send(res,{deleted:true});}));
router.get('/purchases',permit('purchases.view'),ah(async(req,res)=>{if(!op.can(req.user,'pricing.view_cost_price'))throw E.forbidden('Cost visibility required');send(res,(await query('SELECT p.*,s.company_name FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.store_id=$1 ORDER BY p.created_at DESC LIMIT 500',[store(req.user)])).rows);}));
router.post('/purchases',permit('purchases.add'),ah(async(req,res)=>send(res,await op.purchase(req.user,req.body))));
router.get('/purchases/:id',permit('purchases.view','pricing.view_cost_price'),ah(async(req,res)=>{const p=(await query('SELECT p.*,s.company_name FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.id=$1 AND p.store_id=$2',[req.params.id,store(req.user)])).rows[0];if(!p)throw E.notFound('Purchase not found');send(res,{...p,items:(await query('SELECT i.*,p.name,COALESCE((SELECT SUM(quantity) FROM purchase_returns r WHERE r.purchase_item_id=i.id),0) returned_qty FROM purchase_items i JOIN products p ON p.id=i.product_id WHERE purchase_id=$1',[p.id])).rows});}));
router.post('/purchases/:id/return',permit('purchases.return'),requirePin,ah(async(req,res)=>send(res,await withTransaction(async c=>{const p=(await c.query('SELECT * FROM purchases WHERE id=$1 AND store_id=$2 FOR UPDATE',[req.params.id,store(req.user)])).rows[0];if(!p)throw E.notFound('Purchase not found');const i=(await c.query('SELECT i.*,p.hsn_code FROM purchase_items i JOIN products p ON p.id=i.product_id WHERE i.id=$1 AND purchase_id=$2',[req.body.itemId,p.id])).rows[0];if(!i)throw E.notFound('Item not found');const used=(await c.query('SELECT COALESCE(SUM(quantity),0) n FROM purchase_returns WHERE purchase_item_id=$1',[i.id])).rows[0].n;const qty=op.number(req.body.quantity,'quantity',.001,Number(i.quantity)-Number(used));if(!req.body.reason)throw E.badRequest('Return reason required');const amount=op.money(new D(i.total_amount).mul(qty).div(i.quantity)),taxable=op.money(new D(i.taxable_amount).mul(qty).div(i.quantity));const r=(await c.query('INSERT INTO purchase_returns(purchase_id,product_id,purchase_item_id,quantity,reason,amount,taxable_amount,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[p.id,i.product_id,i.id,qty,req.body.reason,amount,taxable,req.user.id])).rows[0];await op.movement(c,req.user,i.product_id,-qty,'purchase_return','purchase_return',r.id,i.batch_id);await op.taxrow(c,'purchase',p.id,{...i,taxable_amount:-taxable,tax:op.money(taxable-amount)},Number(p.igst_amount)>0);await c.query('INSERT INTO debit_notes(supplier_id,purchase_id,amount,reason) VALUES($1,$2,$3,$4)',[p.supplier_id,p.id,amount,req.body.reason]);await op.audit(c,req.user,'purchases.return','purchase_returns',r.id,{amount});return r;}))));
router.get('/purchase-orders',permit('purchases.view'),ah(async(req,res)=>send(res,(await query('SELECT p.*,s.company_name FROM purchase_orders p JOIN suppliers s ON s.id=p.supplier_id WHERE store_id=$1 ORDER BY p.id DESC',[store(req.user)])).rows)));
router.post('/purchase-orders',permit('purchases.add'),ah(async(req,res)=>{if(!req.body.supplierId||!Array.isArray(req.body.items)||!req.body.items.length)throw E.badRequest('Supplier and items required');for(const i of req.body.items)op.number(i.quantity,'quantity',.001);send(res,(await query("INSERT INTO purchase_orders(store_id,supplier_id,po_number,items,expected_date,notes,created_by) VALUES($1,$2,'PO-'||nextval('po_seq'),$3,$4,$5,$6) RETURNING *",[store(req.user),req.body.supplierId,JSON.stringify(req.body.items),req.body.expectedDate||null,req.body.notes,req.user.id])).rows[0]);}));
router.put('/purchase-orders/:id',permit('purchases.approve'),ah(async(req,res)=>{if(!['sent','cancelled'].includes(req.body.status))throw E.badRequest('Invalid status');send(res,(await query("UPDATE purchase_orders SET status=$1 WHERE id=$2 AND store_id=$3 AND status IN('draft','sent') RETURNING *",[req.body.status,req.params.id,store(req.user)])).rows[0]);}));
router.get('/inventory',permit('inventory.view'),ah(async(req,res)=>{let rows=(await query('SELECT s.*,p.name,p.sku,p.reorder_level,p.cost_price,u.short_code unit,b.batch_number,b.expiry_date FROM stock s JOIN products p ON p.id=s.product_id JOIN units u ON u.id=p.unit_id LEFT JOIN product_batches b ON b.id=s.batch_id WHERE s.store_id=$1 ORDER BY p.name,b.expiry_date',[store(req.user)])).rows;if(!op.can(req.user,'pricing.view_cost_price'))rows=rows.map(({cost_price,...r})=>r);send(res,rows);}));
router.get('/inventory/movements',permit('inventory.view'),ah(async(req,res)=>{let rows=(await query('SELECT m.*,p.name,u.full_name FROM stock_movements m JOIN products p ON p.id=m.product_id LEFT JOIN users u ON u.id=m.created_by WHERE m.store_id=$1 ORDER BY m.id DESC LIMIT 1000',[store(req.user)])).rows;if(!op.can(req.user,'pricing.view_cost_price'))rows=rows.map(({cost_rate,...r})=>r);send(res,rows);}));
router.post('/inventory/adjust',permit('inventory.adjust'),requirePin,ah(async(req,res)=>send(res,await withTransaction(async c=>{if(!req.body.reason)throw E.badRequest('Reason required');const qty=op.number(req.body.quantity,'quantity',-1e6,1e6);if(qty===0)throw E.badRequest('Quantity must not be zero');await op.movement(c,req.user,req.body.productId,qty,req.body.type==='damage'?'damage':'adjustment','adjustment',Date.now(),req.body.batchId||null,store(req.user),req.body.reason);await op.audit(c,req.user,'inventory.adjust','stock_movements',req.body.productId,req.body);return {saved:true};}))));
router.post('/inventory/transfer',permit('inventory.transfer'),requirePin,ah(async(req,res)=>send(res,await withTransaction(async c=>{const to=op.number(req.body.toStoreId,'destination store',1);if(to===store(req.user))throw E.badRequest('Choose a different store');const qty=op.number(req.body.quantity,'quantity',.001,1e6);const ref=Date.now();await op.movement(c,req.user,req.body.productId,-qty,'transfer_out','transfer',ref,req.body.batchId||null);await op.movement(c,req.user,req.body.productId,qty,'transfer_in','transfer',ref,req.body.batchId||null,to);await op.audit(c,req.user,'inventory.transfer','stock_movements',ref,req.body);return {saved:true};}))));
router.get('/parties/:type',ah(async(req,res)=>{const type=req.params.type;if(!['customer','supplier'].includes(type))throw E.badRequest('Invalid party type');if(!op.can(req.user,type==='customer'?'customers.view':'suppliers.view'))throw E.forbidden();const ids=(await query(`SELECT id FROM ${type==='customer'?'customers':'suppliers'} ORDER BY id`)).rows;const out=[];for(const {id}of ids)out.push(await withTransaction(c=>op.balance(c,type,id)));send(res,out);}));
router.get('/parties/:type/:id/ledger',ah(async(req,res)=>{const {type,id}=req.params;if(!['customer','supplier'].includes(type))throw E.badRequest('Invalid type');if(!op.can(req.user,type==='customer'?'customers.view':'suppliers.view'))throw E.forbidden();const b=await withTransaction(c=>op.balance(c,type,id));const customer=type==='customer';const inv=(await query(customer?"SELECT created_at,invoice_number description,total_amount debit,0 credit FROM sales WHERE customer_id=$1 AND status='completed' AND invoice_type NOT IN('quotation','estimate')":"SELECT created_at,invoice_number description,total_amount debit,0 credit FROM purchases WHERE supplier_id=$1",[id])).rows;const payments=(await query("SELECT created_at,'Payment / '||mode description,0 debit,amount credit FROM payments WHERE party_type=$1 AND party_id=$2",[type,id])).rows;const returns=(await query(customer?"SELECT r.created_at,'Sales return' description,0 debit,r.amount credit FROM sales_returns r JOIN sales s ON s.id=r.sale_id WHERE s.customer_id=$1":"SELECT r.created_at,'Purchase return' description,0 debit,r.amount credit FROM purchase_returns r JOIN purchases p ON p.id=r.purchase_id WHERE p.supplier_id=$1",[id])).rows;let running=Number(b.party.opening_balance);send(res,{...b,entries:[...inv,...payments,...returns].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(r=>({...r,balance:running=op.money(running+Number(r.debit)-Number(r.credit))}))});}));
router.post('/payments',permit('payments.manage'),ah(async(req,res)=>send(res,await withTransaction(async c=>{const b=req.body;if(!['customer','supplier'].includes(b.partyType)||!['cash','upi','card','bank'].includes(b.mode))throw E.badRequest('Invalid payment');const bal=await op.balance(c,b.partyType,b.partyId);const amount=op.number(b.amount,'amount',.01,Math.max(0,bal.outstanding));const r=(await c.query('INSERT INTO payments(party_type,party_id,reference_type,amount,mode,notes,created_by,store_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[b.partyType,b.partyId,'settlement',amount,b.mode,b.notes,req.user.id,store(req.user)])).rows[0];await op.audit(c,req.user,'payments.create','payments',r.id,{amount});return r;}))));
router.get('/expenses',permit('expenses.manage'),ah(async(req,res)=>send(res,(await query('SELECT * FROM expenses WHERE store_id=$1 ORDER BY expense_date DESC,id DESC LIMIT 1000',[store(req.user)])).rows)));
router.post('/expenses',permit('expenses.manage'),ah(async(req,res)=>send(res,await withTransaction(async c=>{const b=req.body;if(!b.category||!b.description)throw E.badRequest('Category and description required');await op.context(c,req.user,b.expenseDate);const r=(await c.query('INSERT INTO expenses(store_id,expense_date,category,description,amount,payment_mode,vendor,created_by) VALUES($1,COALESCE($2::date,CURRENT_DATE),$3,$4,$5,$6,$7,$8) RETURNING *',[store(req.user),b.expenseDate,b.category,b.description,op.number(b.amount,'amount',.01),b.paymentMode||'cash',b.vendor,req.user.id])).rows[0];await op.audit(c,req.user,'expenses.create','expenses',r.id,{amount:r.amount});return r;}))));
router.get('/settings',permit('settings.manage'),ah(async(req,res)=>send(res,{stores:(await query('SELECT * FROM stores ORDER BY id')).rows,years:(await query('SELECT * FROM financial_years ORDER BY start_date DESC')).rows,settings:Object.fromEntries((await query('SELECT key,value FROM settings')).rows.map(x=>[x.key,x.value])),integrations:{whatsapp:!!process.env.WHATSAPP_ACCESS_TOKEN,sms:!!process.env.MSG91_AUTH_KEY,database:embedded?'embedded PostgreSQL':'PostgreSQL server'}})));
router.put('/settings',permit('settings.manage'),ah(async(req,res)=>send(res,await withTransaction(async c=>{const b=req.body;if(b.store){const s=b.store;if(!s.name)throw E.badRequest('Store name required');await c.query('UPDATE stores SET name=$1,address=$2,gstin=$3,phone=$4,state=$5,state_code=$6 WHERE id=$7',[s.name,s.address,s.gstin||null,s.phone,s.state,s.state_code,store(req.user)]);}for(const [k,v]of Object.entries(b.settings||{})){if(!['invoice_prefix','receipt_footer','store_enabled','store_banner_text','store_min_order_amount','store_delivery_charge','store_public_url'].includes(k))continue;await c.query('INSERT INTO settings(key,value,updated_by) VALUES($1,$2,$3) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_by=EXCLUDED.updated_by,updated_at=now()',[k,JSON.stringify(v),req.user.id]);}await op.audit(c,req.user,'settings.update','settings',store(req.user),{});return {saved:true};}))));
router.post('/stores',permit('settings.manage'),ah(async(req,res)=>{if(!req.body.name)throw E.badRequest('Name required');send(res,(await query('INSERT INTO stores(name,address,state_code) VALUES($1,$2,$3) RETURNING *',[req.body.name,req.body.address,req.body.stateCode||'07'])).rows[0]);}));
router.post('/stores/switch',ah(async(req,res)=>{if(!op.can(req.user,'settings.manage'))throw E.forbidden();const s=(await query('SELECT id FROM stores WHERE id=$1 AND is_active=true',[req.body.storeId])).rows[0];if(!s)throw E.notFound('Store not found');await query('UPDATE users SET store_id=$1 WHERE id=$2',[s.id,req.user.id]);send(res,{storeId:s.id});}));
router.post('/financial-years',permit('settings.manage'),ah(async(req,res)=>{const b=req.body;if(!/^\d{4}-\d{2}$/.test(b.code)||!b.startDate||!b.endDate||b.startDate>=b.endDate)throw E.badRequest('Valid financial year required');if((await query('SELECT id FROM financial_years WHERE start_date<=$1 AND end_date>=$2',[b.endDate,b.startDate])).rows.length)throw E.conflict('Financial years cannot overlap');send(res,(await query('INSERT INTO financial_years(code,start_date,end_date) VALUES($1,$2,$3) RETURNING *',[b.code,b.startDate,b.endDate])).rows[0]);}));
router.get('/backup',permit('backups.manage'),ah(async(req,res)=>{if(!embedded)throw E.badRequest('Use the documented pg_dump command for this PostgreSQL server');await withTransaction(c=>op.audit(c,req.user,'backup.export','settings','backup',{}));const data=await dump();res.set({'Content-Type':'application/gzip','Content-Disposition':`attachment; filename="kirana-backup-${new Date().toISOString().slice(0,10)}.tar.gz"`});res.send(data);}));
module.exports=router;
